services:
  database:
    image: mariadb
    ports:
      - 8079:3306
    volumes:
      - ./database:/var/lib/mysql
    env_file:
      - .env

  wordpress:
    depends_on:
      - database
    image: wordpress:php8.3
    volumes:
      - ./packages:/var/www/html/packages
      - ./vendor:/var/www/html/vendor
      - ./web:/var/www/html/web
      - ./.env:/var/www/html/.env
      - ./.htaccess:/var/www/html/.htaccess
      # Disable images' wordpress install, we'll use the composer version
      - ./web/index.php:/var/www/html/index.php
    ports:
      - 8080:80
    env_file:
      - .env
    configs:
      - source: extra.ini
        target: /usr/local/etc/php/conf.d/extra.ini

  wordpress-cli:
    depends_on:
      - database
      - wordpress
    image: wordpress:cli-php8.3
    volumes:
      - ./vendor:/var/www/html/vendor
      - ./web:/var/www/html/web
      - ./.env:/var/www/html/.env
    env_file:
      - .env

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment: 
      PMA_HOST: database:3306
      UPLOAD_LIMIT: 64M

configs:
  extra.ini:
    content: |
      file_uploads = On
      memory_limit = 512M
      upload_max_filesize = 512M
      post_max_size = 512M
      max_execution_time = 600
