database:
  image: mariadb
  ports:
    - 8079:3306
  volumes:
    - ./database:/var/lib/mysql
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
wordpress:
  image: wordpress
  volumes:
    - ./wordpress:/var/www/html
  ports:
    - 8080:80
  links:
    - database:mysql
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
    - 8081:80
  links:
    - database:db
