name: Build

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        cd web/wp-content/themes/knock-knock
        npm ci
        npm run production
        npm test
      env:
        CI: true
    - name: Pull repo on server, delete twig cache
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        proxy_host: ${{ secrets.SSH_PROXY_HOST }}
        proxy_port: ${{ secrets.SSH_PROXY_PORT }}
        proxy_username: ${{ secrets.SSH_PROXY_USERNAME }}
        proxy_password: ${{ secrets.SSH_PROXY_PASSWORD }}
        script: |
          PATH="/home/${{ secrets.SSH_USERNAME }}/bin/:$PATH"
          cd domains/intranet.klopvaart.nl/public_html && \
          composer-php8 install && \ 
          composer-php8 dump-env prod && \
          rm -r web/wp-content/themes/knock-knock/.twig-cache
    - name: Copy artifacts
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        proxy_host: ${{ secrets.SSH_PROXY_HOST }}
        proxy_port: ${{ secrets.SSH_PROXY_PORT }}
        proxy_username: ${{ secrets.SSH_PROXY_USERNAME }}
        proxy_password: ${{ secrets.SSH_PROXY_PASSWORD }}
        source: "web/wp-content/themes/knock-knock/dist"
        target: "domains/intranet.klopvaart.nl/public_htmlweb/wp-content/themes/knock-knock/dist"