name: Build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.4
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        cd ./wordpress/wp-content/themes/knock-knock
        npm ci
        npm run production
        npm test
      env:
        CI: true
    - name: Install composer dependencies
      run: |
        cd ./wordpress/wp-content/themes/knock-knock
        composer install --prefer-dist --no-progress --no-suggest
    - name: Create empty cache folder
      run: |
        cd ./wordpress/wp-content/themes/knock-knock
        if [ -d ".twig-cache" ]; then rm -Rf .twig-cache; fi
        mkdir .twig-cache
    - name: Delete Twig cache
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_THEME_USER }}
        password: ${{ secrets.FTP_THEME_PASSWORD }}
        local-dir: wordpress/wp-content/themes/knock-knock/.twig-cache/
        server-dir: .twig-cache/
        dangerous-clean-slate: true
    - name: FTP-Deploy-Action theme
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_THEME_USER }}
        password: ${{ secrets.FTP_THEME_PASSWORD }}
        local-dir: ./wordpress/wp-content/themes/knock-knock/
        exclude: node_modules/**
          - node_modules/**/*
          - assets/scss/**
          - assets/js/**
          - .twig-cache
          - webpack.config.js
          - package.json
          - package-lock.json
          - composer.json
          - composer.lock
          - .gitignore
    - name: FTP-Deploy-Action mu-plugins
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_MU_USER }}
        password: ${{ secrets.FTP_MU_PASSWORD }}
        local-dir: ./wordpress/wp-content/mu-plugins/