name: Build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        cd ./wordpress/wp-content/themes/knock-knock
        npm ci
        npm run production
        npm test
      env:
        CI: true
    - name: Install composer dependencies
      run: |
        cd ./wordpress/wp-content/themes/knock-knock
        composer install --prefer-dist --no-progress --no-suggest
    - name: Create empty cache folder
      run: |
        cd ./wordpress/wp-content/themes/knock-knock
        if [ -d ".twig-cache" ]; then rm -Rf .twig-cache; fi
        mkdir .twig-cache
    - name: Delete Twig cache
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USER }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        LOCAL_DIR: wordpress/wp-content/themes/knock-knock/.twig-cache
        REMOTE_DIR: .twig-cache
        ARGS: --delete
    - name: FTP-Deploy-Action theme
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.FTP_HOST }}
        ftp-username: ${{ secrets.FTP_USER }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: wordpress/wp-content/themes/knock-knock/
        git-ftp-args:
    - name: FTP-Deploy-Action mu-plugins
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.FTP_HOST }}
        ftp-username: ${{ secrets.FTP_MU_USER }}
        ftp-password: ${{ secrets.FTP_MU_PASSWORD }}
        local-dir: wordpress/wp-content/mu-plugins