name: Build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        cd ./wordpress/wp-content/themes/knock-knock
        npm ci
        npm run production
        npm test
      env:
        CI: true
    - name: Install composer dependencies
      run: |
        cd ./wordpress/wp-content/themes/knock-knock
        composer install --prefer-dist --no-progress --no-suggest
    - name: FTP-Deploy-Action theme
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: ${{ secrets.FTP_HOST }}
        ftp-username: ${{ secrets.FTP_THEME_USER }}
        ftp-password: ${{ secrets.FTP_THEME_PASSWORD }}
        local-dir: wordpress/wp-content/themes/knock-knock
        git-ftp-args: --exclude=node_modules/ --exclude=.cache/ -L --verbose --dry-run
    - name: FTP-Deploy-Action mu-plugins
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: ${{ secrets.FTP_HOST }}
        ftp-username: ${{ secrets.FTP_MU_USER }}
        ftp-password: ${{ secrets.FTP_MU_PASSWORD }}
        local-dir: wordpress/wp-content/mu-plugins
        git-ftp-args: -L --verbose --dry-run